CREATE DATABASE IF NOT EXISTS `blog_mp`;
CREATE DATABASE IF NOT EXISTS `blog_mp_dev`;
CREATE DATABASE IF NOT EXISTS `blog_mp_test`;

CREATE USER 'blog_mp'@'localhost' IDENTIFIED BY 'changeme';

GRANT USAGE ON *.* TO 'blog_mp'@'localhost' IDENTIFIED BY 'changeme' 
WITH MAX_QUERIES_PER_HOUR 0
MAX_CONNECTIONS_PER_HOUR 0
MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `blog_mp\_%`.* TO 'blog_mp'@'localhost' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `blog_mp`.* TO 'blog_mp'@'localhost' WITH GRANT OPTION;


CREATE USER 'blog_mp'@'%' IDENTIFIED BY 'changeme';
GRANT USAGE ON *.* TO 'blog_mp'@'%' IDENTIFIED BY 'changeme' 
WITH MAX_QUERIES_PER_HOUR 0
MAX_CONNECTIONS_PER_HOUR 0
MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;

GRANT ALL PRIVILEGES ON `blog_mp\_%`.* TO 'blog_mp'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `blog_mp`.* TO 'blog_mp'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
